diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.usebuiltinfsmonitor=true
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=billclintonogot88@gmail.com
user.name=ChiromoHG
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://ChiromoHG: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@github.com/ChiromoHG/chiromo-website.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
